### ISSUE TITLE
ukcensus-query: AttributeError: 'str' object has no attribute 'get_metadata'

### ISSUE THREAD

**Issue by garbit** [virgesmith/UKCensusAPI#40]
Hi there,

I'm getting an error when I run the interactive census builder query:
```
python3 ukcensus-query ~/query-cache
```

I've tried running this with the --no-api-key flag as well but with no effect.

```
python3 ukcensus-query ~/query-cache
Nomisweb census data interactive query builder
See README.md for details on how to use this package
Census table: KS401EW
Traceback (most recent call last):
  File "ukcensus-query", line 37, in <module>
    main(args.cache_dir)
  File "ukcensus-query", line 25, in main
    census.table()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ukcensusapi/Query.py", line 31, in table
    meta = self.api.get_metadata(table)
AttributeError: 'str' object has no attribute 'get_metadata'
```

Thanks,

Andy

**Comment by virgesmith** [comment]
thanks for reporting this, unfortunately I cant replicate, so might need more info fro you. Does  this work for you:
```
"""
KS401EW - Dwellings, household spaces and accommodation type

Code autogenerated by UKCensusAPI
(https://github.com/virgesmith/UKCensusAPI)
"""

# This code requires an API key, see the README.md for details

# Query url:
# https://www.nomisweb.co.uk/api/v01/dataset/NM_618_1.data.tsv?CELL=7...13&MEASURES=20100&RURAL_URBAN=0&date=latest&geography=1245710558...1245710660%2C1245714998...1245714998%2C1245715007...1245715007%2C1245715021...1245715022&select=GEOGRAPHY_CODE%2CCELL%2COBS_VALUE

import ukcensusapi.Nomisweb as CensusApi

api = CensusApi.Nomisweb("/tmp")
table = "KS401EW"
table_internal = "NM_618_1"
query_params = {}
query_params["date"] = "latest"
query_params["select"] = "GEOGRAPHY_CODE,CELL,OBS_VALUE"
query_params["RURAL_URBAN"] = "0"
query_params["CELL"] = "7...13"
query_params["MEASURES"] = "20100"
query_params["geography"] = "1245710558...1245710660,1245714998...1245714998,1245715007...1245715007,1245715021...1245715022"
KS401EW = api.get_data(table, query_params)

print(KS401EW.head())
```
run like so:
```
$ NOMIS_API_KEY=dummy python3 /tmp/KS401EW.py
```
(insert your API key if you have one)

**Comment by virgesmith** [comment]
no response, closing
